language: go

go:
  - 1.12

env:
  - GO111MODULE=on

dist: xenial

addons:
  apt:
    packages:
    - make

script: 
  - go build
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    - srimaln91@gmail.com
